config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  

  get 'foods/show'
  devise_for :foods
   get 'search' => 'food_images#search'
  
   resources :food_images, only: [:new, :create, :index, :show, :destroy]do
      resource :likes, only: [:create, :destroy]
  end
   resources :foods, only: [:show]
   
   resources :users, only: [:show, :edit, :update]
   
   resources :photos, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :food_images, dependent: :destroy
        
end

app/models/food_image.rb
class FoodImage < ApplicationRecord
  belongs_to :food
  attachment :image 
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :likes, dependent: :destroy

  def likes_by?(user)
    likes.where(user_id: user.id).exists?
  end
  
  def self.search(keyword)
  where(["shop_name like? OR address like?", "%#{keyword}%", "%#{keyword}%"])
  end
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :food_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :pf_image
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_food_sign_in_path_for(resource)
    food_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/food_images_controller.rb
class FoodImagesController < ApplicationController
  def new
    @food_image = FoodImage.new
  end

  def create
    @food_image = FoodImage.new(food_image_params)
    @food_image.food_id = current_food.id
    @food_image.save
    redirect_to food_images_path
  end

  def index
    @food_images = FoodImage.page(params[:page]).reverse_order
  end

  def show
     @food_image = FoodImage.find(params[:id])
  end

  def destroy
    @food_image = FoodImage.find(params[:id])
    @food_image.destroy
    redirect_to food_images_path
  end
  
  def search
  @food_images = FoodImage.search(params[:keyword])
  @keyword = params[:keyword]
  render "index"
  end
  
  private

  def food_image_params
    params.require(:food_image).permit(:shop_name, :image, :title, :caption, :hour, :holiday, :address, :latitude, :longitude)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def show
    @food = Food.find(params[:id])
    @food_images = @food.food_images
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   def top
   end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
 def create
    food_image = FoodImage.find(params[:food_image_id])
    like = current_user.likes.new(food_image_id: food_image.id)
    like.save
    redirect_to photo_path(food_image)  
 end

  def destroy
    food_image = FoodImage.find(params[:food_image_id])
    like = current_user.likes.find_by(food_image_id: food_image.id)
    like.destroy
    redirect_to photo_path(food_image)  
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @food_images = FoodImage.page(params[:page]).reverse_order
  end

  def show
     @food_image = FoodImage.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)  
  end
  
  


  private

  def user_params
    params.require(:user).permit(:name, :p_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_images_helper.rb
module FoodImagesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/phots_helper.rb
module PhotsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food_images/index.html.erb
<div class=background>
<div class="container">
  <div class="row">
    <div class="food-list">
    <% @food_images.each do |food_image| %>
    <% end %>
    </div>

    <div class="col-lg-9 offset-lg-1">
      <div class="mb-3">
        <div class="search-form">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
        <% end %>
        </div>
      </div>

      <div class="all-card">
       <% @food_images.each do |food_image| %>
        <div class="card mb-2 mx-3">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <td>
                 <%= link_to food_image_path(food_image.id) do %>
                 <%= attachment_image_tag food_image, :image,size: "auto", format: 'jpg' %>
                 <% end %>
                </td>
              </tr>
              <tr>
                <td>店舗名[<%= food_image.shop_name %>]</td>
              </tr>
              <tr>
                <td>タイトル[<%= food_image.title %>]</td>
              </tr>
              <tr>
                <td>告知内容[<%= food_image.caption %>]</td>
              </tr>
            </tbody>
          </table>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>
</div

app/views/food_images/new.html.erb
<div class=background>
  <div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">
          <strong>店舗投稿フォーム</strong>
      </h5>
<%= form_with model: @food_image, local:true do |f| %>

<div class="col text-center">
            <table class="table table-borderless">
                <tbody>
                  <tr><td><h4>店舗名</h4></td>
                  <td><%= f.text_field :shop_name %></td>
                  </tr>
                  
                  <tr><td><h4>タイトル</h4></td>
                  <td><%= f.text_field :title %></td>
                  </tr> 
                  
                  <tr><td><h4>説明</h4></td>
                  <td><%= f.text_area :caption %></td>
                  </tr>
                  
                  <tr><td><h4>アクセス</h4></td>
                  <td> <%= f.text_field :address, placeholder: "住所" %></td>
                  </tr>
                        
                  <tr><td><h4>営業時間</h4></td>
                  <td> <%= f.text_field :hour %></td>
                  </tr>  
                  
                  <tr><td><h4>休業日</h4></td>
                  <td> <%= f.text_field :holiday %></td>
                  </tr>   
                  
                  <tr><td><h4>画像</h4></td>
                  <td> <%= f.attachment_field :image %></td>
                  </tr>
                </tbody>
            </table>
            <div class="col text-center">
                <%= f.submit "投稿" ,class: 'btn btn-lg btn-warning btn-block' %>
            </div>
        </div>
    </div>
</div>
</div>
<% end %>
</div>

app/views/food_images/show.html.erb
<div class=background>
<div class="container">
  <div class="row">
    <div class="card-big-one col-lg-10 d-flex align-items-center">
    <div><%= attachment_image_tag @food_image, :image , size: "800×600", format: 'jpeg' %></div>
  <div class="col-lg-8">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>
                <div>
                  <% if @food_image.food == current_food %>
                  <%= link_to "削除", food_image_path(@food_image), method: :delete %>
                  <% end %>
                </div>
              </td>
            </tr>
            <tr>
                <td><p>店舗名：<%= @food_image.shop_name %></p></td>
            </tr>
            <tr>
              <td><p><%= @food_image.title %></p></td>
            </tr>
            <tr>
              <td><p><%= @food_image.caption %></p></p></td>
            </tr>
            <tr>
              <td><p>営業時間：<%= @food_image.hour %></p></td>
            </tr>
            <tr>
              <td><p>休業日：<%= @food_image.holiday %></p></td>
            </tr>
            <tr>
              <td><p>アクセス：<%= @food_image.address %></p><div id='map'></div></td>
            </tr>
          </tbody>
        </table>
    </div>



        <style>
        #map{
          width: 340px;
          height: 250px;
        }
        </style>

        <script>
          let map
          let geocoder

          function initMap(){
            // geocoderを初期化
           var test ={lat: <%= @food_image.latitude %>, lng: <%= @food_image.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @food_image.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

 
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }

        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>
 </div> 
 </div>
 </div>

app/views/foods/show.html.erb
<p><%= @food.name %>Mypage</p>
<% @food_images.each do |food_image| %>
<div>
  <%= link_to food_image_path(food_image.id) do %>
  <%= attachment_image_tag food_image, :image %>
  <% end %>
  <p>店舗名：<%= food_image.shop_name %></p>
  <p>投稿タイトル:<%= food_image.title %></p>
  <p>説明：<%= food_image.caption %></p>
<% end %>

app/views/homes/top.html.erb
<div class="home-container ">
  <div class="row">
    <div class="col">
      <div class="application-title text-center">
        <h1>Meshimatch</h1>
        <p>食べてみたいを探したい。</p>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<div class="background">
<div class="container">
  <div class="row">
    <div class="food-list">
    <% @food_images.each do |food_image| %>
    <% end %>
    </div>

    <div class="col-lg-9 offset-lg-1">
      <div class="mb-3">
        <div class="search-form">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
        <% end %>
        </div>
      </div>

      <div class="all-card">
       <% @food_images.each do |food_image| %>
        <div class="card mb-2 mx-3">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <td>
                 <%= link_to photo_path(food_image.id) do %>
                 <%= attachment_image_tag food_image, :image,size: "au", format: 'jpg' %>
                 <% end %>
                </td>
              </tr>
              <tr>
                <td>店舗名[<%= food_image.shop_name %>]</td>
              </tr>
              <tr>
                <td>タイトル[<%= food_image.title %>]</td>
              </tr>
              <tr>
                <td>[<%= food_image.caption %>]</td>
              </tr>
            </tbody>
          </table>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>
</div>

app/views/photos/show.html.erb
<div class="background">
<div class="container">
  <div class="row">
    <div class="card-big-one col-lg-10 d-flex align-items-center">
    <div><%= attachment_image_tag @food_image, :image , size: "800×600", format: 'jpeg' %></div>
  <div class="col-lg-8">
        <table class="table table-borderless">
          <tbody>
            <tr>
                <td><p>店舗名：<%= @food_image.shop_name %></p>
                <% if @food_image.likes_by?(current_user) %>
                <p>
                <%= link_to food_image_likes_path(@food_image), method: :delete do %>
                <i class="far fa-heart like-btn" ><%= @food_image.likes.count %></i>
                <% end %>
                </p>
                <% else %>
                <p>
                <%= link_to food_image_likes_path(@food_image), method: :post do %>
                <i class="far fa-heart like-btn" ><%= @food_image.likes.count %></i>
                <% end %>
                </p>
                <% end %>
                </td>
            </tr>
            <tr>
              <td><p><%= @food_image.title %></p></td>
            </tr>
            <tr>
              <td><p><%= @food_image.caption %></p></p></td>
            </tr>
            <tr>
              <td><p>営業時間：<%= @food_image.hour %></p></td>
            </tr>
            <tr>
              <td><p>休業日：<%= @food_image.holiday %></p></td>
            </tr>
            <tr>
              <td><p>アクセス：<%= @food_image.address %></p><div id='map'></div></td>
            </tr>
          </tbody>
        </table>
    </div>



        <style>
        #map{
          width: 340px;
          height: 250px;
        }
        </style>

        <script>
          let map
          let geocoder

          function initMap(){
            // geocoderを初期化
           var test ={lat: <%= @food_image.latitude %>, lng: <%= @food_image.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @food_image.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

 
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }

        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>
 </div> 
 </div>
 </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row d-flex align-items-center text-center">
    <div class="col-lg-4 my-3">
      <h3>Edit</h3>
    </div>

   <%= form_with model:@user, local:true do |f| %>
    <div class="col-lg-8">
      <div class="form-group row my-4">
        <%= f.label(:pf_image, "プロフィール画像") %>
        <%= f.attachment_field :pf_image, class:"form-control-file", placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group row my-4">
        <%= f.label(:name, "登録名の変更（2文字以上10文字以下）") %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group mt-5">
        <%= f.submit "保存", class:"btn btn-yellow" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class=background>
<div class="container">
  <div class="row d-flex align-items-center text-center">
    <div class="col-lg-2 my-3">
      <h3><%= @user.name %>My page</h3>
    </div>

    <div class="col-lg-4">
      <%= attachment_image_tag @user, :pf_image, class: "profile-image-to-circle", size:'300x300', format: 'jpg', fallback: 'user.jpg' %>
    </div>

    <div class="col-lg-6">
      <table class="table table-borderless mb-5">
        <tbody>
          <tr>
            <td>ニックネーム</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to "プロフィール編集", edit_user_path(@user), class:"btn btn-edit" %>
      </div>
    </div>
  </div>
</div>
</div>