config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  

  get 'foods/show'
  devise_for :foods
   get 'search' => 'food_images#search'
  
   resources :food_images, only: [:new, :create, :index, :show, :destroy]do
      resource :likes, only: [:create, :destroy]
  end
   resources :foods, only: [:show]
   
   resources :users, only: [:show, :edit, :update]
   
   resources :photos, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :food_images, dependent: :destroy
        
end

app/models/food_image.rb
class FoodImage < ApplicationRecord
  belongs_to :food
  attachment :image 
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :likes, dependent: :destroy

  def likes_by?(user)
    likes.where(user_id: user.id).exists?
  end
  
  def self.search(keyword)
  where(["shop_name like? OR address like?", "%#{keyword}%", "%#{keyword}%"])
  end
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :food_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :pf_image
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_food_sign_in_path_for(resource)
    food_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def show
    @food = Food.find(params[:id])
    @food_images = @food.food_images
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   def top
   end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
 def create
    food_image = FoodImage.find(params[:food_image_id])
    like = current_user.likes.new(food_image_id: food_image.id)
    like.save
    redirect_to photo_path(food_image)  
 end

  def destroy
    food_image = FoodImage.find(params[:food_image_id])
    like = current_user.likes.find_by(food_image_id: food_image.id)
    like.destroy
    redirect_to photo_path(food_image)  
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @food_images = FoodImage.page(params[:page]).reverse_order
  end

  def show
     @food_image = FoodImage.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)  
  end
  
  


  private

  def user_params
    params.require(:user).permit(:name, :p_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_images_helper.rb
module FoodImagesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/phots_helper.rb
module PhotsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshimatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav-color">
      <div>
        <nav class = "navbar navbar-expand-lg">
          <div class="container">
             <a class="navbar-brand p-1" href="/"><%= image_tag('Meshimatch.png') %></a>
            
            <ul class = "navbar-nav ml-auto">
              <% if user_signed_in? %>
                
                <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "Meshi探し", photos_path, class: "text-dark" %>
                </button>
                
                <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "Mypage", user_path(current_user.id) , class: "text-dark" %>
                </button>
          
                <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "log out", destroy_user_session_path, method: :delete,  class: "text-dark" %>
                </button>
              <% elsif food_signed_in? %>
              <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "投稿", new_food_image_path, class: "text-dark" %>
              </button>
              <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "投稿一覧", food_images_path, class: "text-dark" %>
                </button>
              
                <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "log out", destroy_food_session_path, method: :delete, class: "text-dark" %>
                </button>
              <% else %>
               <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "USER sign up", new_user_registration_path, class: "text-dark" %>
                </button>
                
                <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "USER log in", new_user_session_path, class: "text-dark" %>
                </button>
             
              <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to " Food sign in", new_food_registration_path, class: "text-dark" %>
              </button>
             
             <button type="button" class="btn btn-warning text-light border rounded mx-3">
                <%= link_to "Food log in", new_food_session_path, class: "text-dark" %>
             </button>
              <% end %>
            </ul>
            <!--</div>-->
        </div>
      </nav>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>